import { SidebarLink } from "@/types"

export const themes = [
  { value: "light", label: "Light", icon: "/assets/icons/sun.svg" },
  { value: "dark", label: "Dark", icon: "/assets/icons/moon.svg" },
  { value: "system", label: "System", icon: "/assets/icons/computer.svg" },
]

export const sidebarLinks: SidebarLink[] = [
  {
    imgURL: "/assets/icons/home.svg",
    route: "/",
    label: "Home",
  },
  {
    imgURL: "/assets/icons/users.svg",
    route: "/community",
    label: "Community",
  },
  {
    imgURL: "/assets/icons/star.svg",
    route: "/collection",
    label: "Collections",
  },
  {
    imgURL: "/assets/icons/suitcase.svg",
    route: "/jobs",
    label: "Find Jobs",
  },
  {
    imgURL: "/assets/icons/tag.svg",
    route: "/tags",
    label: "Tags",
  },
  {
    imgURL: "/assets/icons/user.svg",
    route: "/profile",
    label: "Profile",
  },
  {
    imgURL: "/assets/icons/question.svg",
    route: "/ask-question",
    label: "Ask a question",
  },
]

export const BADGE_CRITERIA = {
  QUESTION_COUNT: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  ANSWER_COUNT: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  QUESTION_UPVOTES: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  ANSWER_UPVOTES: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  TOTAL_VIEWS: {
    BRONZE: 1000,
    SILVER: 10000,
    GOLD: 100000,
  },
}

export const rightSideBarList = [
  {
    _id: "1",
    title:
      "Would it be appropriate to point out an error in another paper during a referee report?",
  },
  { _id: "2", title: "How can an airconditioning machine exist?" },

  { _id: "3", title: "How to make a good diagram of a lattice?" },

  { _id: "4", title: "Interrogated every time crossing UK Border as citizen" },

  {
    _id: "5",
    title: "What is an example of 3 numbers that do not make up a vector?",
  },
]

export const rightSideBarTags = [
  { _id: "1", name: "javascript", count: 20152 },
  {
    _id: "2",
    name: "next.js",
    count: 18493,
  },
  {
    _id: "3",
    name: "react.js",
    count: 16269,
  },
  { _id: "4", name: "node.js", count: 15121 },
  {
    _id: "5",
    name: "python",
    count: 14431,
  },
  {
    _id: "6",
    name: "postgresql",
    count: 9429,
  },
]

export const countries = [
  {
    name: "Afghanistan",
    alpha2Code: "AF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    independent: false,
  },
  {
    name: "Åland Islands",
    alpha2Code: "AX",
    flag: "https://flagcdn.com/ax.svg",
    independent: false,
  },
  {
    name: "Albania",
    alpha2Code: "AL",
    flag: "https://flagcdn.com/al.svg",
    independent: false,
  },
  {
    name: "Algeria",
    alpha2Code: "DZ",
    flag: "https://flagcdn.com/dz.svg",
    independent: false,
  },
  {
    name: "American Samoa",
    alpha2Code: "AS",
    flag: "https://flagcdn.com/as.svg",
    independent: false,
  },
  {
    name: "Andorra",
    alpha2Code: "AD",
    flag: "https://flagcdn.com/ad.svg",
    independent: false,
  },
  {
    name: "Angola",
    alpha2Code: "AO",
    flag: "https://flagcdn.com/ao.svg",
    independent: false,
  },
  {
    name: "Anguilla",
    alpha2Code: "AI",
    flag: "https://flagcdn.com/ai.svg",
    independent: false,
  },
  {
    name: "Antarctica",
    alpha2Code: "AQ",
    flag: "https://flagcdn.com/aq.svg",
    independent: false,
  },
  {
    name: "Antigua and Barbuda",
    alpha2Code: "AG",
    flag: "https://flagcdn.com/ag.svg",
    independent: false,
  },
  {
    name: "Argentina",
    alpha2Code: "AR",
    flag: "https://flagcdn.com/ar.svg",
    independent: false,
  },
  {
    name: "Armenia",
    alpha2Code: "AM",
    flag: "https://flagcdn.com/am.svg",
    independent: false,
  },
  {
    name: "Aruba",
    alpha2Code: "AW",
    flag: "https://flagcdn.com/aw.svg",
    independent: false,
  },
  {
    name: "Australia",
    alpha2Code: "AU",
    flag: "https://flagcdn.com/au.svg",
    independent: false,
  },
  {
    name: "Austria",
    alpha2Code: "AT",
    flag: "https://flagcdn.com/at.svg",
    independent: false,
  },
  {
    name: "Azerbaijan",
    alpha2Code: "AZ",
    flag: "https://flagcdn.com/az.svg",
    independent: false,
  },
  {
    name: "Bahamas",
    alpha2Code: "BS",
    flag: "https://flagcdn.com/bs.svg",
    independent: false,
  },
  {
    name: "Bahrain",
    alpha2Code: "BH",
    flag: "https://flagcdn.com/bh.svg",
    independent: false,
  },
  {
    name: "Bangladesh",
    alpha2Code: "BD",
    flag: "https://flagcdn.com/bd.svg",
    independent: false,
  },
  {
    name: "Barbados",
    alpha2Code: "BB",
    flag: "https://flagcdn.com/bb.svg",
    independent: false,
  },
  {
    name: "Belarus",
    alpha2Code: "BY",
    flag: "https://flagcdn.com/by.svg",
    independent: false,
  },
  {
    name: "Belgium",
    alpha2Code: "BE",
    flag: "https://flagcdn.com/be.svg",
    independent: false,
  },
  {
    name: "Belize",
    alpha2Code: "BZ",
    flag: "https://flagcdn.com/bz.svg",
    independent: false,
  },
  {
    name: "Benin",
    alpha2Code: "BJ",
    flag: "https://flagcdn.com/bj.svg",
    independent: false,
  },
  {
    name: "Bermuda",
    alpha2Code: "BM",
    flag: "https://flagcdn.com/bm.svg",
    independent: false,
  },
  {
    name: "Bhutan",
    alpha2Code: "BT",
    flag: "https://flagcdn.com/bt.svg",
    independent: false,
  },
  {
    name: "Bolivia (Plurinational State of)",
    alpha2Code: "BO",
    flag: "https://flagcdn.com/bo.svg",
    independent: false,
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    alpha2Code: "BQ",
    flag: "https://flagcdn.com/bq.svg",
    independent: false,
  },
  {
    name: "Bosnia and Herzegovina",
    alpha2Code: "BA",
    flag: "https://flagcdn.com/ba.svg",
    independent: false,
  },
  {
    name: "Botswana",
    alpha2Code: "BW",
    flag: "https://flagcdn.com/bw.svg",
    independent: false,
  },
  {
    name: "Bouvet Island",
    alpha2Code: "BV",
    flag: "https://flagcdn.com/bv.svg",
    independent: false,
  },
  {
    name: "Brazil",
    alpha2Code: "BR",
    flag: "https://flagcdn.com/br.svg",
    independent: false,
  },
  {
    name: "British Indian Ocean Territory",
    alpha2Code: "IO",
    flag: "https://flagcdn.com/io.svg",
    independent: false,
  },
  {
    name: "United States Minor Outlying Islands",
    alpha2Code: "UM",
    flag: "https://flagcdn.com/um.svg",
    independent: false,
  },
  {
    name: "Virgin Islands (British)",
    alpha2Code: "VG",
    flag: "https://flagcdn.com/vg.svg",
    independent: false,
  },
  {
    name: "Virgin Islands (U.S.)",
    alpha2Code: "VI",
    flag: "https://flagcdn.com/vi.svg",
    independent: false,
  },
  {
    name: "Brunei Darussalam",
    alpha2Code: "BN",
    flag: "https://flagcdn.com/bn.svg",
    independent: false,
  },
  {
    name: "Bulgaria",
    alpha2Code: "BG",
    flag: "https://flagcdn.com/bg.svg",
    independent: false,
  },
  {
    name: "Burkina Faso",
    alpha2Code: "BF",
    flag: "https://flagcdn.com/bf.svg",
    independent: false,
  },
  {
    name: "Burundi",
    alpha2Code: "BI",
    flag: "https://flagcdn.com/bi.svg",
    independent: false,
  },
  {
    name: "Cambodia",
    alpha2Code: "KH",
    flag: "https://flagcdn.com/kh.svg",
    independent: false,
  },
  {
    name: "Cameroon",
    alpha2Code: "CM",
    flag: "https://flagcdn.com/cm.svg",
    independent: false,
  },
  {
    name: "Canada",
    alpha2Code: "CA",
    flag: "https://flagcdn.com/ca.svg",
    independent: false,
  },
  {
    name: "Cabo Verde",
    alpha2Code: "CV",
    flag: "https://flagcdn.com/cv.svg",
    independent: false,
  },
  {
    name: "Cayman Islands",
    alpha2Code: "KY",
    flag: "https://flagcdn.com/ky.svg",
    independent: false,
  },
  {
    name: "Central African Republic",
    alpha2Code: "CF",
    flag: "https://flagcdn.com/cf.svg",
    independent: false,
  },
  {
    name: "Chad",
    alpha2Code: "TD",
    flag: "https://flagcdn.com/td.svg",
    independent: false,
  },
  {
    name: "Chile",
    alpha2Code: "CL",
    flag: "https://flagcdn.com/cl.svg",
    independent: false,
  },
  {
    name: "China",
    alpha2Code: "CN",
    flag: "https://flagcdn.com/cn.svg",
    independent: false,
  },
  {
    name: "Christmas Island",
    alpha2Code: "CX",
    flag: "https://flagcdn.com/cx.svg",
    independent: false,
  },
  {
    name: "Cocos (Keeling) Islands",
    alpha2Code: "CC",
    flag: "https://flagcdn.com/cc.svg",
    independent: false,
  },
  {
    name: "Colombia",
    alpha2Code: "CO",
    flag: "https://flagcdn.com/co.svg",
    independent: false,
  },
  {
    name: "Comoros",
    alpha2Code: "KM",
    flag: "https://flagcdn.com/km.svg",
    independent: false,
  },
  {
    name: "Congo",
    alpha2Code: "CG",
    flag: "https://flagcdn.com/cg.svg",
    independent: false,
  },
  {
    name: "Congo (Democratic Republic of the)",
    alpha2Code: "CD",
    flag: "https://flagcdn.com/cd.svg",
    independent: false,
  },
  {
    name: "Cook Islands",
    alpha2Code: "CK",
    flag: "https://flagcdn.com/ck.svg",
    independent: false,
  },
  {
    name: "Costa Rica",
    alpha2Code: "CR",
    flag: "https://flagcdn.com/cr.svg",
    independent: false,
  },
  {
    name: "Croatia",
    alpha2Code: "HR",
    flag: "https://flagcdn.com/hr.svg",
    independent: false,
  },
  {
    name: "Cuba",
    alpha2Code: "CU",
    flag: "https://flagcdn.com/cu.svg",
    independent: false,
  },
  {
    name: "Curaçao",
    alpha2Code: "CW",
    flag: "https://flagcdn.com/cw.svg",
    independent: false,
  },
  {
    name: "Cyprus",
    alpha2Code: "CY",
    flag: "https://flagcdn.com/cy.svg",
    independent: false,
  },
  {
    name: "Czech Republic",
    alpha2Code: "CZ",
    flag: "https://flagcdn.com/cz.svg",
    independent: false,
  },
  {
    name: "Denmark",
    alpha2Code: "DK",
    flag: "https://flagcdn.com/dk.svg",
    independent: false,
  },
  {
    name: "Djibouti",
    alpha2Code: "DJ",
    flag: "https://flagcdn.com/dj.svg",
    independent: false,
  },
  {
    name: "Dominica",
    alpha2Code: "DM",
    flag: "https://flagcdn.com/dm.svg",
    independent: false,
  },
  {
    name: "Dominican Republic",
    alpha2Code: "DO",
    flag: "https://flagcdn.com/do.svg",
    independent: false,
  },
  {
    name: "Ecuador",
    alpha2Code: "EC",
    flag: "https://flagcdn.com/ec.svg",
    independent: false,
  },
  {
    name: "Egypt",
    alpha2Code: "EG",
    flag: "https://flagcdn.com/eg.svg",
    independent: false,
  },
  {
    name: "El Salvador",
    alpha2Code: "SV",
    flag: "https://flagcdn.com/sv.svg",
    independent: false,
  },
  {
    name: "Equatorial Guinea",
    alpha2Code: "GQ",
    flag: "https://flagcdn.com/gq.svg",
    independent: false,
  },
  {
    name: "Eritrea",
    alpha2Code: "ER",
    flag: "https://flagcdn.com/er.svg",
    independent: false,
  },
  {
    name: "Estonia",
    alpha2Code: "EE",
    flag: "https://flagcdn.com/ee.svg",
    independent: false,
  },
  {
    name: "Ethiopia",
    alpha2Code: "ET",
    flag: "https://flagcdn.com/et.svg",
    independent: false,
  },
  {
    name: "Falkland Islands (Malvinas)",
    alpha2Code: "FK",
    flag: "https://flagcdn.com/fk.svg",
    independent: false,
  },
  {
    name: "Faroe Islands",
    alpha2Code: "FO",
    flag: "https://flagcdn.com/fo.svg",
    independent: false,
  },
  {
    name: "Fiji",
    alpha2Code: "FJ",
    flag: "https://flagcdn.com/fj.svg",
    independent: false,
  },
  {
    name: "Finland",
    alpha2Code: "FI",
    flag: "https://flagcdn.com/fi.svg",
    independent: false,
  },
  {
    name: "France",
    alpha2Code: "FR",
    flag: "https://flagcdn.com/fr.svg",
    independent: false,
  },
  {
    name: "French Guiana",
    alpha2Code: "GF",
    flag: "https://flagcdn.com/gf.svg",
    independent: false,
  },
  {
    name: "French Polynesia",
    alpha2Code: "PF",
    flag: "https://flagcdn.com/pf.svg",
    independent: false,
  },
  {
    name: "French Southern Territories",
    alpha2Code: "TF",
    flag: "https://flagcdn.com/tf.svg",
    independent: false,
  },
  {
    name: "Gabon",
    alpha2Code: "GA",
    flag: "https://flagcdn.com/ga.svg",
    independent: false,
  },
  {
    name: "Gambia",
    alpha2Code: "GM",
    flag: "https://flagcdn.com/gm.svg",
    independent: false,
  },
  {
    name: "Georgia",
    alpha2Code: "GE",
    flag: "https://flagcdn.com/ge.svg",
    independent: false,
  },
  {
    name: "Germany",
    alpha2Code: "DE",
    flag: "https://flagcdn.com/de.svg",
    independent: false,
  },
  {
    name: "Ghana",
    alpha2Code: "GH",
    flag: "https://flagcdn.com/gh.svg",
    independent: false,
  },
  {
    name: "Gibraltar",
    alpha2Code: "GI",
    flag: "https://flagcdn.com/gi.svg",
    independent: false,
  },
  {
    name: "Greece",
    alpha2Code: "GR",
    flag: "https://flagcdn.com/gr.svg",
    independent: false,
  },
  {
    name: "Greenland",
    alpha2Code: "GL",
    flag: "https://flagcdn.com/gl.svg",
    independent: false,
  },
  {
    name: "Grenada",
    alpha2Code: "GD",
    flag: "https://flagcdn.com/gd.svg",
    independent: false,
  },
  {
    name: "Guadeloupe",
    alpha2Code: "GP",
    flag: "https://flagcdn.com/gp.svg",
    independent: false,
  },
  {
    name: "Guam",
    alpha2Code: "GU",
    flag: "https://flagcdn.com/gu.svg",
    independent: false,
  },
  {
    name: "Guatemala",
    alpha2Code: "GT",
    flag: "https://flagcdn.com/gt.svg",
    independent: false,
  },
  {
    name: "Guernsey",
    alpha2Code: "GG",
    flag: "https://flagcdn.com/gg.svg",
    independent: false,
  },
  {
    name: "Guinea",
    alpha2Code: "GN",
    flag: "https://flagcdn.com/gn.svg",
    independent: false,
  },
  {
    name: "Guinea-Bissau",
    alpha2Code: "GW",
    flag: "https://flagcdn.com/gw.svg",
    independent: false,
  },
  {
    name: "Guyana",
    alpha2Code: "GY",
    flag: "https://flagcdn.com/gy.svg",
    independent: false,
  },
  {
    name: "Haiti",
    alpha2Code: "HT",
    flag: "https://flagcdn.com/ht.svg",
    independent: false,
  },
  {
    name: "Heard Island and McDonald Islands",
    alpha2Code: "HM",
    flag: "https://flagcdn.com/hm.svg",
    independent: false,
  },
  {
    name: "Vatican City",
    alpha2Code: "VA",
    flag: "https://flagcdn.com/va.svg",
    independent: false,
  },
  {
    name: "Honduras",
    alpha2Code: "HN",
    flag: "https://flagcdn.com/hn.svg",
    independent: false,
  },
  {
    name: "Hungary",
    alpha2Code: "HU",
    flag: "https://flagcdn.com/hu.svg",
    independent: false,
  },
  {
    name: "Hong Kong",
    alpha2Code: "HK",
    flag: "https://flagcdn.com/hk.svg",
    independent: false,
  },
  {
    name: "Iceland",
    alpha2Code: "IS",
    flag: "https://flagcdn.com/is.svg",
    independent: false,
  },
  {
    name: "India",
    alpha2Code: "IN",
    flag: "https://flagcdn.com/in.svg",
    independent: false,
  },
  {
    name: "Indonesia",
    alpha2Code: "ID",
    flag: "https://flagcdn.com/id.svg",
    independent: false,
  },
  {
    name: "Ivory Coast",
    alpha2Code: "CI",
    flag: "https://flagcdn.com/ci.svg",
    independent: false,
  },
  {
    name: "Iran (Islamic Republic of)",
    alpha2Code: "IR",
    flag: "https://flagcdn.com/ir.svg",
    independent: false,
  },
  {
    name: "Iraq",
    alpha2Code: "IQ",
    flag: "https://flagcdn.com/iq.svg",
    independent: false,
  },
  {
    name: "Ireland",
    alpha2Code: "IE",
    flag: "https://flagcdn.com/ie.svg",
    independent: false,
  },
  {
    name: "Isle of Man",
    alpha2Code: "IM",
    flag: "https://flagcdn.com/im.svg",
    independent: false,
  },
  {
    name: "Israel",
    alpha2Code: "IL",
    flag: "https://flagcdn.com/il.svg",
    independent: false,
  },
  {
    name: "Italy",
    alpha2Code: "IT",
    flag: "https://flagcdn.com/it.svg",
    independent: false,
  },
  {
    name: "Jamaica",
    alpha2Code: "JM",
    flag: "https://flagcdn.com/jm.svg",
    independent: false,
  },
  {
    name: "Japan",
    alpha2Code: "JP",
    flag: "https://flagcdn.com/jp.svg",
    independent: false,
  },
  {
    name: "Jersey",
    alpha2Code: "JE",
    flag: "https://flagcdn.com/je.svg",
    independent: false,
  },
  {
    name: "Jordan",
    alpha2Code: "JO",
    flag: "https://flagcdn.com/jo.svg",
    independent: false,
  },
  {
    name: "Kazakhstan",
    alpha2Code: "KZ",
    flag: "https://flagcdn.com/kz.svg",
    independent: false,
  },
  {
    name: "Kenya",
    alpha2Code: "KE",
    flag: "https://flagcdn.com/ke.svg",
    independent: false,
  },
  {
    name: "Kiribati",
    alpha2Code: "KI",
    flag: "https://flagcdn.com/ki.svg",
    independent: false,
  },
  {
    name: "Kuwait",
    alpha2Code: "KW",
    flag: "https://flagcdn.com/kw.svg",
    independent: false,
  },
  {
    name: "Kyrgyzstan",
    alpha2Code: "KG",
    flag: "https://flagcdn.com/kg.svg",
    independent: false,
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2Code: "LA",
    flag: "https://flagcdn.com/la.svg",
    independent: false,
  },
  {
    name: "Latvia",
    alpha2Code: "LV",
    flag: "https://flagcdn.com/lv.svg",
    independent: false,
  },
  {
    name: "Lebanon",
    alpha2Code: "LB",
    flag: "https://flagcdn.com/lb.svg",
    independent: false,
  },
  {
    name: "Lesotho",
    alpha2Code: "LS",
    flag: "https://flagcdn.com/ls.svg",
    independent: false,
  },
  {
    name: "Liberia",
    alpha2Code: "LR",
    flag: "https://flagcdn.com/lr.svg",
    independent: false,
  },
  {
    name: "Libya",
    alpha2Code: "LY",
    flag: "https://flagcdn.com/ly.svg",
    independent: false,
  },
  {
    name: "Liechtenstein",
    alpha2Code: "LI",
    flag: "https://flagcdn.com/li.svg",
    independent: false,
  },
  {
    name: "Lithuania",
    alpha2Code: "LT",
    flag: "https://flagcdn.com/lt.svg",
    independent: false,
  },
  {
    name: "Luxembourg",
    alpha2Code: "LU",
    flag: "https://flagcdn.com/lu.svg",
    independent: false,
  },
  {
    name: "Macao",
    alpha2Code: "MO",
    flag: "https://flagcdn.com/mo.svg",
    independent: false,
  },
  {
    name: "North Macedonia",
    alpha2Code: "MK",
    flag: "https://flagcdn.com/mk.svg",
    independent: false,
  },
  {
    name: "Madagascar",
    alpha2Code: "MG",
    flag: "https://flagcdn.com/mg.svg",
    independent: false,
  },
  {
    name: "Malawi",
    alpha2Code: "MW",
    flag: "https://flagcdn.com/mw.svg",
    independent: false,
  },
  {
    name: "Malaysia",
    alpha2Code: "MY",
    flag: "https://flagcdn.com/my.svg",
    independent: false,
  },
  {
    name: "Maldives",
    alpha2Code: "MV",
    flag: "https://flagcdn.com/mv.svg",
    independent: false,
  },
  {
    name: "Mali",
    alpha2Code: "ML",
    flag: "https://flagcdn.com/ml.svg",
    independent: false,
  },
  {
    name: "Malta",
    alpha2Code: "MT",
    flag: "https://flagcdn.com/mt.svg",
    independent: false,
  },
  {
    name: "Marshall Islands",
    alpha2Code: "MH",
    flag: "https://flagcdn.com/mh.svg",
    independent: false,
  },
  {
    name: "Martinique",
    alpha2Code: "MQ",
    flag: "https://flagcdn.com/mq.svg",
    independent: false,
  },
  {
    name: "Mauritania",
    alpha2Code: "MR",
    flag: "https://flagcdn.com/mr.svg",
    independent: false,
  },
  {
    name: "Mauritius",
    alpha2Code: "MU",
    flag: "https://flagcdn.com/mu.svg",
    independent: false,
  },
  {
    name: "Mayotte",
    alpha2Code: "YT",
    flag: "https://flagcdn.com/yt.svg",
    independent: false,
  },
  {
    name: "Mexico",
    alpha2Code: "MX",
    flag: "https://flagcdn.com/mx.svg",
    independent: false,
  },
  {
    name: "Micronesia (Federated States of)",
    alpha2Code: "FM",
    flag: "https://flagcdn.com/fm.svg",
    independent: false,
  },
  {
    name: "Moldova (Republic of)",
    alpha2Code: "MD",
    flag: "https://flagcdn.com/md.svg",
    independent: false,
  },
  {
    name: "Monaco",
    alpha2Code: "MC",
    flag: "https://flagcdn.com/mc.svg",
    independent: false,
  },
  {
    name: "Mongolia",
    alpha2Code: "MN",
    flag: "https://flagcdn.com/mn.svg",
    independent: false,
  },
  {
    name: "Montenegro",
    alpha2Code: "ME",
    flag: "https://flagcdn.com/me.svg",
    independent: false,
  },
  {
    name: "Montserrat",
    alpha2Code: "MS",
    flag: "https://flagcdn.com/ms.svg",
    independent: false,
  },
  {
    name: "Morocco",
    alpha2Code: "MA",
    flag: "https://flagcdn.com/ma.svg",
    independent: false,
  },
  {
    name: "Mozambique",
    alpha2Code: "MZ",
    flag: "https://flagcdn.com/mz.svg",
    independent: false,
  },
  {
    name: "Myanmar",
    alpha2Code: "MM",
    flag: "https://flagcdn.com/mm.svg",
    independent: false,
  },
  {
    name: "Namibia",
    alpha2Code: "NA",
    flag: "https://flagcdn.com/na.svg",
    independent: false,
  },
  {
    name: "Nauru",
    alpha2Code: "NR",
    flag: "https://flagcdn.com/nr.svg",
    independent: false,
  },
  {
    name: "Nepal",
    alpha2Code: "NP",
    flag: "https://flagcdn.com/np.svg",
    independent: false,
  },
  {
    name: "Netherlands",
    alpha2Code: "NL",
    flag: "https://flagcdn.com/nl.svg",
    independent: false,
  },
  {
    name: "New Caledonia",
    alpha2Code: "NC",
    flag: "https://flagcdn.com/nc.svg",
    independent: false,
  },
  {
    name: "New Zealand",
    alpha2Code: "NZ",
    flag: "https://flagcdn.com/nz.svg",
    independent: false,
  },
  {
    name: "Nicaragua",
    alpha2Code: "NI",
    flag: "https://flagcdn.com/ni.svg",
    independent: false,
  },
  {
    name: "Niger",
    alpha2Code: "NE",
    flag: "https://flagcdn.com/ne.svg",
    independent: false,
  },
  {
    name: "Nigeria",
    alpha2Code: "NG",
    flag: "https://flagcdn.com/ng.svg",
    independent: false,
  },
  {
    name: "Niue",
    alpha2Code: "NU",
    flag: "https://flagcdn.com/nu.svg",
    independent: false,
  },
  {
    name: "Norfolk Island",
    alpha2Code: "NF",
    flag: "https://flagcdn.com/nf.svg",
    independent: false,
  },
  {
    name: "Korea (Democratic People's Republic of)",
    alpha2Code: "KP",
    flag: "https://flagcdn.com/kp.svg",
    independent: false,
  },
  {
    name: "Northern Mariana Islands",
    alpha2Code: "MP",
    flag: "https://flagcdn.com/mp.svg",
    independent: false,
  },
  {
    name: "Norway",
    alpha2Code: "NO",
    flag: "https://flagcdn.com/no.svg",
    independent: false,
  },
  {
    name: "Oman",
    alpha2Code: "OM",
    flag: "https://flagcdn.com/om.svg",
    independent: false,
  },
  {
    name: "Pakistan",
    alpha2Code: "PK",
    flag: "https://flagcdn.com/pk.svg",
    independent: false,
  },
  {
    name: "Palau",
    alpha2Code: "PW",
    flag: "https://flagcdn.com/pw.svg",
    independent: false,
  },
  {
    name: "Palestine, State of",
    alpha2Code: "PS",
    flag: "https://flagcdn.com/ps.svg",
    independent: false,
  },
  {
    name: "Panama",
    alpha2Code: "PA",
    flag: "https://flagcdn.com/pa.svg",
    independent: false,
  },
  {
    name: "Papua New Guinea",
    alpha2Code: "PG",
    flag: "https://flagcdn.com/pg.svg",
    independent: false,
  },
  {
    name: "Paraguay",
    alpha2Code: "PY",
    flag: "https://flagcdn.com/py.svg",
    independent: false,
  },
  {
    name: "Peru",
    alpha2Code: "PE",
    flag: "https://flagcdn.com/pe.svg",
    independent: false,
  },
  {
    name: "Philippines",
    alpha2Code: "PH",
    flag: "https://flagcdn.com/ph.svg",
    independent: false,
  },
  {
    name: "Pitcairn",
    alpha2Code: "PN",
    flag: "https://flagcdn.com/pn.svg",
    independent: false,
  },
  {
    name: "Poland",
    alpha2Code: "PL",
    flag: "https://flagcdn.com/pl.svg",
    independent: false,
  },
  {
    name: "Portugal",
    alpha2Code: "PT",
    flag: "https://flagcdn.com/pt.svg",
    independent: false,
  },
  {
    name: "Puerto Rico",
    alpha2Code: "PR",
    flag: "https://flagcdn.com/pr.svg",
    independent: false,
  },
  {
    name: "Qatar",
    alpha2Code: "QA",
    flag: "https://flagcdn.com/qa.svg",
    independent: false,
  },
  {
    name: "Republic of Kosovo",
    alpha2Code: "XK",
    flag: "https://flagcdn.com/xk.svg",
    independent: false,
  },
  {
    name: "Réunion",
    alpha2Code: "RE",
    flag: "https://flagcdn.com/re.svg",
    independent: false,
  },
  {
    name: "Romania",
    alpha2Code: "RO",
    flag: "https://flagcdn.com/ro.svg",
    independent: false,
  },
  {
    name: "Russian Federation",
    alpha2Code: "RU",
    flag: "https://flagcdn.com/ru.svg",
    independent: false,
  },
  {
    name: "Rwanda",
    alpha2Code: "RW",
    flag: "https://flagcdn.com/rw.svg",
    independent: false,
  },
  {
    name: "Saint Barthélemy",
    alpha2Code: "BL",
    flag: "https://flagcdn.com/bl.svg",
    independent: false,
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    alpha2Code: "SH",
    flag: "https://flagcdn.com/sh.svg",
    independent: false,
  },
  {
    name: "Saint Kitts and Nevis",
    alpha2Code: "KN",
    flag: "https://flagcdn.com/kn.svg",
    independent: false,
  },
  {
    name: "Saint Lucia",
    alpha2Code: "LC",
    flag: "https://flagcdn.com/lc.svg",
    independent: false,
  },
  {
    name: "Saint Martin (French part)",
    alpha2Code: "MF",
    flag: "https://flagcdn.com/mf.svg",
    independent: false,
  },
  {
    name: "Saint Pierre and Miquelon",
    alpha2Code: "PM",
    flag: "https://flagcdn.com/pm.svg",
    independent: false,
  },
  {
    name: "Saint Vincent and the Grenadines",
    alpha2Code: "VC",
    flag: "https://flagcdn.com/vc.svg",
    independent: false,
  },
  {
    name: "Samoa",
    alpha2Code: "WS",
    flag: "https://flagcdn.com/ws.svg",
    independent: false,
  },
  {
    name: "San Marino",
    alpha2Code: "SM",
    flag: "https://flagcdn.com/sm.svg",
    independent: false,
  },
  {
    name: "Sao Tome and Principe",
    alpha2Code: "ST",
    flag: "https://flagcdn.com/st.svg",
    independent: false,
  },
  {
    name: "Saudi Arabia",
    alpha2Code: "SA",
    flag: "https://flagcdn.com/sa.svg",
    independent: false,
  },
  {
    name: "Senegal",
    alpha2Code: "SN",
    flag: "https://flagcdn.com/sn.svg",
    independent: false,
  },
  {
    name: "Serbia",
    alpha2Code: "RS",
    flag: "https://flagcdn.com/rs.svg",
    independent: false,
  },
  {
    name: "Seychelles",
    alpha2Code: "SC",
    flag: "https://flagcdn.com/sc.svg",
    independent: false,
  },
  {
    name: "Sierra Leone",
    alpha2Code: "SL",
    flag: "https://flagcdn.com/sl.svg",
    independent: false,
  },
  {
    name: "Singapore",
    alpha2Code: "SG",
    flag: "https://flagcdn.com/sg.svg",
    independent: false,
  },
  {
    name: "Sint Maarten (Dutch part)",
    alpha2Code: "SX",
    flag: "https://flagcdn.com/sx.svg",
    independent: false,
  },
  {
    name: "Slovakia",
    alpha2Code: "SK",
    flag: "https://flagcdn.com/sk.svg",
    independent: false,
  },
  {
    name: "Slovenia",
    alpha2Code: "SI",
    flag: "https://flagcdn.com/si.svg",
    independent: false,
  },
  {
    name: "Solomon Islands",
    alpha2Code: "SB",
    flag: "https://flagcdn.com/sb.svg",
    independent: false,
  },
  {
    name: "Somalia",
    alpha2Code: "SO",
    flag: "https://flagcdn.com/so.svg",
    independent: false,
  },
  {
    name: "South Africa",
    alpha2Code: "ZA",
    flag: "https://flagcdn.com/za.svg",
    independent: false,
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    alpha2Code: "GS",
    flag: "https://flagcdn.com/gs.svg",
    independent: false,
  },
  {
    name: "Korea (Republic of)",
    alpha2Code: "KR",
    flag: "https://flagcdn.com/kr.svg",
    independent: false,
  },
  {
    name: "Spain",
    alpha2Code: "ES",
    flag: "https://flagcdn.com/es.svg",
    independent: false,
  },
  {
    name: "Sri Lanka",
    alpha2Code: "LK",
    flag: "https://flagcdn.com/lk.svg",
    independent: false,
  },
  {
    name: "Sudan",
    alpha2Code: "SD",
    flag: "https://flagcdn.com/sd.svg",
    independent: false,
  },
  {
    name: "South Sudan",
    alpha2Code: "SS",
    flag: "https://flagcdn.com/ss.svg",
    independent: false,
  },
  {
    name: "Suriname",
    alpha2Code: "SR",
    flag: "https://flagcdn.com/sr.svg",
    independent: false,
  },
  {
    name: "Svalbard and Jan Mayen",
    alpha2Code: "SJ",
    flag: "https://flagcdn.com/sj.svg",
    independent: false,
  },
  {
    name: "Swaziland",
    alpha2Code: "SZ",
    flag: "https://flagcdn.com/sz.svg",
    independent: false,
  },
  {
    name: "Sweden",
    alpha2Code: "SE",
    flag: "https://flagcdn.com/se.svg",
    independent: false,
  },
  {
    name: "Switzerland",
    alpha2Code: "CH",
    flag: "https://flagcdn.com/ch.svg",
    independent: false,
  },
  {
    name: "Syrian Arab Republic",
    alpha2Code: "SY",
    flag: "https://flagcdn.com/sy.svg",
    independent: false,
  },
  {
    name: "Taiwan",
    alpha2Code: "TW",
    flag: "https://flagcdn.com/tw.svg",
    independent: false,
  },
  {
    name: "Tajikistan",
    alpha2Code: "TJ",
    flag: "https://flagcdn.com/tj.svg",
    independent: false,
  },
  {
    name: "Tanzania, United Republic of",
    alpha2Code: "TZ",
    flag: "https://flagcdn.com/tz.svg",
    independent: false,
  },
  {
    name: "Thailand",
    alpha2Code: "TH",
    flag: "https://flagcdn.com/th.svg",
    independent: false,
  },
  {
    name: "Timor-Leste",
    alpha2Code: "TL",
    flag: "https://flagcdn.com/tl.svg",
    independent: false,
  },
  {
    name: "Togo",
    alpha2Code: "TG",
    flag: "https://flagcdn.com/tg.svg",
    independent: false,
  },
  {
    name: "Tokelau",
    alpha2Code: "TK",
    flag: "https://flagcdn.com/tk.svg",
    independent: false,
  },
  {
    name: "Tonga",
    alpha2Code: "TO",
    flag: "https://flagcdn.com/to.svg",
    independent: false,
  },
  {
    name: "Trinidad and Tobago",
    alpha2Code: "TT",
    flag: "https://flagcdn.com/tt.svg",
    independent: false,
  },
  {
    name: "Tunisia",
    alpha2Code: "TN",
    flag: "https://flagcdn.com/tn.svg",
    independent: false,
  },
  {
    name: "Turkey",
    alpha2Code: "TR",
    flag: "https://flagcdn.com/tr.svg",
    independent: false,
  },
  {
    name: "Turkmenistan",
    alpha2Code: "TM",
    flag: "https://flagcdn.com/tm.svg",
    independent: false,
  },
  {
    name: "Turks and Caicos Islands",
    alpha2Code: "TC",
    flag: "https://flagcdn.com/tc.svg",
    independent: false,
  },
  {
    name: "Tuvalu",
    alpha2Code: "TV",
    flag: "https://flagcdn.com/tv.svg",
    independent: false,
  },
  {
    name: "Uganda",
    alpha2Code: "UG",
    flag: "https://flagcdn.com/ug.svg",
    independent: false,
  },
  {
    name: "Ukraine",
    alpha2Code: "UA",
    flag: "https://flagcdn.com/ua.svg",
    independent: false,
  },
  {
    name: "United Arab Emirates",
    alpha2Code: "AE",
    flag: "https://flagcdn.com/ae.svg",
    independent: false,
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    alpha2Code: "GB",
    flag: "https://flagcdn.com/gb.svg",
    independent: false,
  },
  {
    name: "United States of America",
    alpha2Code: "US",
    flag: "https://flagcdn.com/us.svg",
    independent: false,
  },
  {
    name: "Uruguay",
    alpha2Code: "UY",
    flag: "https://flagcdn.com/uy.svg",
    independent: false,
  },
  {
    name: "Uzbekistan",
    alpha2Code: "UZ",
    flag: "https://flagcdn.com/uz.svg",
    independent: false,
  },
  {
    name: "Vanuatu",
    alpha2Code: "VU",
    flag: "https://flagcdn.com/vu.svg",
    independent: false,
  },
  {
    name: "Venezuela (Bolivarian Republic of)",
    alpha2Code: "VE",
    flag: "https://flagcdn.com/ve.svg",
    independent: false,
  },
  {
    name: "Vietnam",
    alpha2Code: "VN",
    flag: "https://flagcdn.com/vn.svg",
    independent: false,
  },
  {
    name: "Wallis and Futuna",
    alpha2Code: "WF",
    flag: "https://flagcdn.com/wf.svg",
    independent: false,
  },
  {
    name: "Western Sahara",
    alpha2Code: "EH",
    flag: "https://flagcdn.com/eh.svg",
    independent: false,
  },
  {
    name: "Yemen",
    alpha2Code: "YE",
    flag: "https://flagcdn.com/ye.svg",
    independent: false,
  },
  {
    name: "Zambia",
    alpha2Code: "ZM",
    flag: "https://flagcdn.com/zm.svg",
    independent: false,
  },
  {
    name: "Zimbabwe",
    alpha2Code: "ZW",
    flag: "https://flagcdn.com/zw.svg",
    independent: false,
  },
]
